pipeline {
    agent any
    environment {
        GIT_URL = "https://github.com/rossm932/SpringBoot-API---BookCab-Project.git"
        IMAGE_NAME = "bookcabapp"
    }
    stages {
        stage('Clone Repository') {
            steps {
                echo "Cloning Git repository..."
                git branch: 'main', url: GIT_URL
            }
        }
        stage('Maven Build') {
            steps {
                echo "Building Spring Boot application..."
                sh './mvnw clean package -DskipTests'
            }
        }
        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh 'docker build -t ${IMAGE_NAME} .'
            }
        }
        stage('Run Docker Container') {
            steps {
                echo "Starting Docker container..."
                sh 'docker run -d -p 8080:8080 ${IMAGE_NAME}'
            }
        }
    }
}

